name: Auto

on:
  schedule:
    - cron: "30 01 * * *" # 北京时间上午10:30
  workflow_dispatch:

env:
  COOKIE: ${{ secrets.COOKIE }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
  DU_TOKEN: ${{ secrets.DU_TOKEN }}
  DU_COOKIE: ${{ secrets.DU_COOKIE }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  JIAOTONG_COOKIE: ${{ secrets.JIAOTONG_COOKIE }}
  JIAOTONG_TOKEN: ${{ secrets.JIAOTONG_TOKEN }}
jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
          yarn du
          yarn masdb
          yarn jiaotong
  # SeaGold:
  #   needs: CheckIn
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #     - name: Run Project
  #       run: |
  #         cd workflows
  #         yarn
  #         yarn seagold
